//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: google/cloud/tasks/v2beta3/cloudtasks.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Cloud Tasks allows developers to manage the execution of background
/// work in their applications.
///
/// Usage: instantiate `Google_Cloud_Tasks_V2beta3_CloudTasksClient`, then call methods of this protocol to make API calls.
public protocol Google_Cloud_Tasks_V2beta3_CloudTasksClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Google_Cloud_Tasks_V2beta3_CloudTasksClientInterceptorFactoryProtocol? { get }

  func listQueues(
    _ request: Google_Cloud_Tasks_V2beta3_ListQueuesRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_ListQueuesRequest, Google_Cloud_Tasks_V2beta3_ListQueuesResponse>

  func getQueue(
    _ request: Google_Cloud_Tasks_V2beta3_GetQueueRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_GetQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>

  func createQueue(
    _ request: Google_Cloud_Tasks_V2beta3_CreateQueueRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_CreateQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>

  func updateQueue(
    _ request: Google_Cloud_Tasks_V2beta3_UpdateQueueRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_UpdateQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>

  func deleteQueue(
    _ request: Google_Cloud_Tasks_V2beta3_DeleteQueueRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_DeleteQueueRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func purgeQueue(
    _ request: Google_Cloud_Tasks_V2beta3_PurgeQueueRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_PurgeQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>

  func pauseQueue(
    _ request: Google_Cloud_Tasks_V2beta3_PauseQueueRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_PauseQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>

  func resumeQueue(
    _ request: Google_Cloud_Tasks_V2beta3_ResumeQueueRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_ResumeQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>

  func getIamPolicy(
    _ request: Google_Iam_V1_GetIamPolicyRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Iam_V1_GetIamPolicyRequest, Google_Iam_V1_Policy>

  func setIamPolicy(
    _ request: Google_Iam_V1_SetIamPolicyRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Iam_V1_SetIamPolicyRequest, Google_Iam_V1_Policy>

  func testIamPermissions(
    _ request: Google_Iam_V1_TestIamPermissionsRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Iam_V1_TestIamPermissionsRequest, Google_Iam_V1_TestIamPermissionsResponse>

  func listTasks(
    _ request: Google_Cloud_Tasks_V2beta3_ListTasksRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_ListTasksRequest, Google_Cloud_Tasks_V2beta3_ListTasksResponse>

  func getTask(
    _ request: Google_Cloud_Tasks_V2beta3_GetTaskRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_GetTaskRequest, Google_Cloud_Tasks_V2beta3_Task>

  func createTask(
    _ request: Google_Cloud_Tasks_V2beta3_CreateTaskRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_CreateTaskRequest, Google_Cloud_Tasks_V2beta3_Task>

  func deleteTask(
    _ request: Google_Cloud_Tasks_V2beta3_DeleteTaskRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_DeleteTaskRequest, SwiftProtobuf.Google_Protobuf_Empty>

  func runTask(
    _ request: Google_Cloud_Tasks_V2beta3_RunTaskRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_RunTaskRequest, Google_Cloud_Tasks_V2beta3_Task>
}

extension Google_Cloud_Tasks_V2beta3_CloudTasksClientProtocol {
  public var serviceName: String {
    return "google.cloud.tasks.v2beta3.CloudTasks"
  }

  /// Lists queues.
  ///
  /// Queues are returned in lexicographical order.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListQueues.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listQueues(
    _ request: Google_Cloud_Tasks_V2beta3_ListQueuesRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_ListQueuesRequest, Google_Cloud_Tasks_V2beta3_ListQueuesResponse> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/ListQueues",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListQueuesInterceptors() ?? []
    )
  }

  /// Gets a queue.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetQueue.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getQueue(
    _ request: Google_Cloud_Tasks_V2beta3_GetQueueRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_GetQueueRequest, Google_Cloud_Tasks_V2beta3_Queue> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/GetQueue",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetQueueInterceptors() ?? []
    )
  }

  /// Creates a queue.
  ///
  /// Queues created with this method allow tasks to live for a maximum of 31
  /// days. After a task is 31 days old, the task will be deleted regardless of whether
  /// it was dispatched or not.
  ///
  /// WARNING: Using this method may have unintended side effects if you are
  /// using an App Engine `queue.yaml` or `queue.xml` file to manage your queues.
  /// Read
  /// [Overview of Queue Management and
  /// queue.yaml](https://cloud.google.com/tasks/docs/queue-yaml) before using
  /// this method.
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateQueue.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func createQueue(
    _ request: Google_Cloud_Tasks_V2beta3_CreateQueueRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_CreateQueueRequest, Google_Cloud_Tasks_V2beta3_Queue> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/CreateQueue",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateQueueInterceptors() ?? []
    )
  }

  /// Updates a queue.
  ///
  /// This method creates the queue if it does not exist and updates
  /// the queue if it does exist.
  ///
  /// Queues created with this method allow tasks to live for a maximum of 31
  /// days. After a task is 31 days old, the task will be deleted regardless of whether
  /// it was dispatched or not.
  ///
  /// WARNING: Using this method may have unintended side effects if you are
  /// using an App Engine `queue.yaml` or `queue.xml` file to manage your queues.
  /// Read
  /// [Overview of Queue Management and
  /// queue.yaml](https://cloud.google.com/tasks/docs/queue-yaml) before using
  /// this method.
  ///
  /// - Parameters:
  ///   - request: Request to send to UpdateQueue.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func updateQueue(
    _ request: Google_Cloud_Tasks_V2beta3_UpdateQueueRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_UpdateQueueRequest, Google_Cloud_Tasks_V2beta3_Queue> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/UpdateQueue",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpdateQueueInterceptors() ?? []
    )
  }

  /// Deletes a queue.
  ///
  /// This command will delete the queue even if it has tasks in it.
  ///
  /// Note: If you delete a queue, a queue with the same name can't be created
  /// for 7 days.
  ///
  /// WARNING: Using this method may have unintended side effects if you are
  /// using an App Engine `queue.yaml` or `queue.xml` file to manage your queues.
  /// Read
  /// [Overview of Queue Management and
  /// queue.yaml](https://cloud.google.com/tasks/docs/queue-yaml) before using
  /// this method.
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteQueue.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func deleteQueue(
    _ request: Google_Cloud_Tasks_V2beta3_DeleteQueueRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_DeleteQueueRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/DeleteQueue",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteQueueInterceptors() ?? []
    )
  }

  /// Purges a queue by deleting all of its tasks.
  ///
  /// All tasks created before this method is called are permanently deleted.
  ///
  /// Purge operations can take up to one minute to take effect. Tasks
  /// might be dispatched before the purge takes effect. A purge is irreversible.
  ///
  /// - Parameters:
  ///   - request: Request to send to PurgeQueue.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func purgeQueue(
    _ request: Google_Cloud_Tasks_V2beta3_PurgeQueueRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_PurgeQueueRequest, Google_Cloud_Tasks_V2beta3_Queue> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/PurgeQueue",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePurgeQueueInterceptors() ?? []
    )
  }

  /// Pauses the queue.
  ///
  /// If a queue is paused then the system will stop dispatching tasks
  /// until the queue is resumed via
  /// [ResumeQueue][google.cloud.tasks.v2beta3.CloudTasks.ResumeQueue]. Tasks can still be added
  /// when the queue is paused. A queue is paused if its
  /// [state][google.cloud.tasks.v2beta3.Queue.state] is [PAUSED][google.cloud.tasks.v2beta3.Queue.State.PAUSED].
  ///
  /// - Parameters:
  ///   - request: Request to send to PauseQueue.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func pauseQueue(
    _ request: Google_Cloud_Tasks_V2beta3_PauseQueueRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_PauseQueueRequest, Google_Cloud_Tasks_V2beta3_Queue> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/PauseQueue",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makePauseQueueInterceptors() ?? []
    )
  }

  /// Resume a queue.
  ///
  /// This method resumes a queue after it has been
  /// [PAUSED][google.cloud.tasks.v2beta3.Queue.State.PAUSED] or
  /// [DISABLED][google.cloud.tasks.v2beta3.Queue.State.DISABLED]. The state of a queue is stored
  /// in the queue's [state][google.cloud.tasks.v2beta3.Queue.state]; after calling this method it
  /// will be set to [RUNNING][google.cloud.tasks.v2beta3.Queue.State.RUNNING].
  ///
  /// WARNING: Resuming many high-QPS queues at the same time can
  /// lead to target overloading. If you are resuming high-QPS
  /// queues, follow the 500/50/5 pattern described in
  /// [Managing Cloud Tasks Scaling
  /// Risks](https://cloud.google.com/tasks/docs/manage-cloud-task-scaling).
  ///
  /// - Parameters:
  ///   - request: Request to send to ResumeQueue.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func resumeQueue(
    _ request: Google_Cloud_Tasks_V2beta3_ResumeQueueRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_ResumeQueueRequest, Google_Cloud_Tasks_V2beta3_Queue> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/ResumeQueue",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeResumeQueueInterceptors() ?? []
    )
  }

  /// Gets the access control policy for a [Queue][google.cloud.tasks.v2beta3.Queue].
  /// Returns an empty policy if the resource exists and does not have a policy
  /// set.
  ///
  /// Authorization requires the following
  /// [Google IAM](https://cloud.google.com/iam) permission on the specified
  /// resource parent:
  ///
  /// * `cloudtasks.queues.getIamPolicy`
  ///
  /// - Parameters:
  ///   - request: Request to send to GetIamPolicy.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getIamPolicy(
    _ request: Google_Iam_V1_GetIamPolicyRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Iam_V1_GetIamPolicyRequest, Google_Iam_V1_Policy> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/GetIamPolicy",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetIamPolicyInterceptors() ?? []
    )
  }

  /// Sets the access control policy for a [Queue][google.cloud.tasks.v2beta3.Queue]. Replaces any existing
  /// policy.
  ///
  /// Note: The Cloud Console does not check queue-level IAM permissions yet.
  /// Project-level permissions are required to use the Cloud Console.
  ///
  /// Authorization requires the following
  /// [Google IAM](https://cloud.google.com/iam) permission on the specified
  /// resource parent:
  ///
  /// * `cloudtasks.queues.setIamPolicy`
  ///
  /// - Parameters:
  ///   - request: Request to send to SetIamPolicy.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func setIamPolicy(
    _ request: Google_Iam_V1_SetIamPolicyRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Iam_V1_SetIamPolicyRequest, Google_Iam_V1_Policy> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/SetIamPolicy",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSetIamPolicyInterceptors() ?? []
    )
  }

  /// Returns permissions that a caller has on a [Queue][google.cloud.tasks.v2beta3.Queue].
  /// If the resource does not exist, this will return an empty set of
  /// permissions, not a [NOT_FOUND][google.rpc.Code.NOT_FOUND] error.
  ///
  /// Note: This operation is designed to be used for building permission-aware
  /// UIs and command-line tools, not for authorization checking. This operation
  /// may "fail open" without warning.
  ///
  /// - Parameters:
  ///   - request: Request to send to TestIamPermissions.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func testIamPermissions(
    _ request: Google_Iam_V1_TestIamPermissionsRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Iam_V1_TestIamPermissionsRequest, Google_Iam_V1_TestIamPermissionsResponse> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/TestIamPermissions",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeTestIamPermissionsInterceptors() ?? []
    )
  }

  /// Lists the tasks in a queue.
  ///
  /// By default, only the [BASIC][google.cloud.tasks.v2beta3.Task.View.BASIC] view is retrieved
  /// due to performance considerations;
  /// [response_view][google.cloud.tasks.v2beta3.ListTasksRequest.response_view] controls the
  /// subset of information which is returned.
  ///
  /// The tasks may be returned in any order. The ordering may change at any
  /// time.
  ///
  /// - Parameters:
  ///   - request: Request to send to ListTasks.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func listTasks(
    _ request: Google_Cloud_Tasks_V2beta3_ListTasksRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_ListTasksRequest, Google_Cloud_Tasks_V2beta3_ListTasksResponse> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/ListTasks",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeListTasksInterceptors() ?? []
    )
  }

  /// Gets a task.
  ///
  /// - Parameters:
  ///   - request: Request to send to GetTask.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getTask(
    _ request: Google_Cloud_Tasks_V2beta3_GetTaskRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_GetTaskRequest, Google_Cloud_Tasks_V2beta3_Task> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/GetTask",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetTaskInterceptors() ?? []
    )
  }

  /// Creates a task and adds it to a queue.
  ///
  /// Tasks cannot be updated after creation; there is no UpdateTask command.
  ///
  /// * The maximum task size is 100KB.
  ///
  /// - Parameters:
  ///   - request: Request to send to CreateTask.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func createTask(
    _ request: Google_Cloud_Tasks_V2beta3_CreateTaskRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_CreateTaskRequest, Google_Cloud_Tasks_V2beta3_Task> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/CreateTask",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeCreateTaskInterceptors() ?? []
    )
  }

  /// Deletes a task.
  ///
  /// A task can be deleted if it is scheduled or dispatched. A task
  /// cannot be deleted if it has executed successfully or permanently
  /// failed.
  ///
  /// - Parameters:
  ///   - request: Request to send to DeleteTask.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func deleteTask(
    _ request: Google_Cloud_Tasks_V2beta3_DeleteTaskRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_DeleteTaskRequest, SwiftProtobuf.Google_Protobuf_Empty> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/DeleteTask",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeDeleteTaskInterceptors() ?? []
    )
  }

  /// Forces a task to run now.
  ///
  /// When this method is called, Cloud Tasks will dispatch the task, even if
  /// the task is already running, the queue has reached its [RateLimits][google.cloud.tasks.v2beta3.RateLimits] or
  /// is [PAUSED][google.cloud.tasks.v2beta3.Queue.State.PAUSED].
  ///
  /// This command is meant to be used for manual debugging. For
  /// example, [RunTask][google.cloud.tasks.v2beta3.CloudTasks.RunTask] can be used to retry a failed
  /// task after a fix has been made or to manually force a task to be
  /// dispatched now.
  ///
  /// The dispatched task is returned. That is, the task that is returned
  /// contains the [status][Task.status] after the task is dispatched but
  /// before the task is received by its target.
  ///
  /// If Cloud Tasks receives a successful response from the task's
  /// target, then the task will be deleted; otherwise the task's
  /// [schedule_time][google.cloud.tasks.v2beta3.Task.schedule_time] will be reset to the time that
  /// [RunTask][google.cloud.tasks.v2beta3.CloudTasks.RunTask] was called plus the retry delay specified
  /// in the queue's [RetryConfig][google.cloud.tasks.v2beta3.RetryConfig].
  ///
  /// [RunTask][google.cloud.tasks.v2beta3.CloudTasks.RunTask] returns
  /// [NOT_FOUND][google.rpc.Code.NOT_FOUND] when it is called on a
  /// task that has already succeeded or permanently failed.
  ///
  /// - Parameters:
  ///   - request: Request to send to RunTask.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func runTask(
    _ request: Google_Cloud_Tasks_V2beta3_RunTaskRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Google_Cloud_Tasks_V2beta3_RunTaskRequest, Google_Cloud_Tasks_V2beta3_Task> {
    return self.makeUnaryCall(
      path: "/google.cloud.tasks.v2beta3.CloudTasks/RunTask",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeRunTaskInterceptors() ?? []
    )
  }
}

public protocol Google_Cloud_Tasks_V2beta3_CloudTasksClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'listQueues'.
  func makeListQueuesInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_ListQueuesRequest, Google_Cloud_Tasks_V2beta3_ListQueuesResponse>]

  /// - Returns: Interceptors to use when invoking 'getQueue'.
  func makeGetQueueInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_GetQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>]

  /// - Returns: Interceptors to use when invoking 'createQueue'.
  func makeCreateQueueInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_CreateQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>]

  /// - Returns: Interceptors to use when invoking 'updateQueue'.
  func makeUpdateQueueInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_UpdateQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>]

  /// - Returns: Interceptors to use when invoking 'deleteQueue'.
  func makeDeleteQueueInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_DeleteQueueRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when invoking 'purgeQueue'.
  func makePurgeQueueInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_PurgeQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>]

  /// - Returns: Interceptors to use when invoking 'pauseQueue'.
  func makePauseQueueInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_PauseQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>]

  /// - Returns: Interceptors to use when invoking 'resumeQueue'.
  func makeResumeQueueInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_ResumeQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>]

  /// - Returns: Interceptors to use when invoking 'getIamPolicy'.
  func makeGetIamPolicyInterceptors() -> [ClientInterceptor<Google_Iam_V1_GetIamPolicyRequest, Google_Iam_V1_Policy>]

  /// - Returns: Interceptors to use when invoking 'setIamPolicy'.
  func makeSetIamPolicyInterceptors() -> [ClientInterceptor<Google_Iam_V1_SetIamPolicyRequest, Google_Iam_V1_Policy>]

  /// - Returns: Interceptors to use when invoking 'testIamPermissions'.
  func makeTestIamPermissionsInterceptors() -> [ClientInterceptor<Google_Iam_V1_TestIamPermissionsRequest, Google_Iam_V1_TestIamPermissionsResponse>]

  /// - Returns: Interceptors to use when invoking 'listTasks'.
  func makeListTasksInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_ListTasksRequest, Google_Cloud_Tasks_V2beta3_ListTasksResponse>]

  /// - Returns: Interceptors to use when invoking 'getTask'.
  func makeGetTaskInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_GetTaskRequest, Google_Cloud_Tasks_V2beta3_Task>]

  /// - Returns: Interceptors to use when invoking 'createTask'.
  func makeCreateTaskInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_CreateTaskRequest, Google_Cloud_Tasks_V2beta3_Task>]

  /// - Returns: Interceptors to use when invoking 'deleteTask'.
  func makeDeleteTaskInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_DeleteTaskRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when invoking 'runTask'.
  func makeRunTaskInterceptors() -> [ClientInterceptor<Google_Cloud_Tasks_V2beta3_RunTaskRequest, Google_Cloud_Tasks_V2beta3_Task>]
}

public final class Google_Cloud_Tasks_V2beta3_CloudTasksClient: Google_Cloud_Tasks_V2beta3_CloudTasksClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Google_Cloud_Tasks_V2beta3_CloudTasksClientInterceptorFactoryProtocol?

  /// Creates a client for the google.cloud.tasks.v2beta3.CloudTasks service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Google_Cloud_Tasks_V2beta3_CloudTasksClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// Cloud Tasks allows developers to manage the execution of background
/// work in their applications.
///
/// To build a server, implement a class that conforms to this protocol.
public protocol Google_Cloud_Tasks_V2beta3_CloudTasksProvider: CallHandlerProvider {
  var interceptors: Google_Cloud_Tasks_V2beta3_CloudTasksServerInterceptorFactoryProtocol? { get }

  /// Lists queues.
  ///
  /// Queues are returned in lexicographical order.
  func listQueues(request: Google_Cloud_Tasks_V2beta3_ListQueuesRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Tasks_V2beta3_ListQueuesResponse>

  /// Gets a queue.
  func getQueue(request: Google_Cloud_Tasks_V2beta3_GetQueueRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Tasks_V2beta3_Queue>

  /// Creates a queue.
  ///
  /// Queues created with this method allow tasks to live for a maximum of 31
  /// days. After a task is 31 days old, the task will be deleted regardless of whether
  /// it was dispatched or not.
  ///
  /// WARNING: Using this method may have unintended side effects if you are
  /// using an App Engine `queue.yaml` or `queue.xml` file to manage your queues.
  /// Read
  /// [Overview of Queue Management and
  /// queue.yaml](https://cloud.google.com/tasks/docs/queue-yaml) before using
  /// this method.
  func createQueue(request: Google_Cloud_Tasks_V2beta3_CreateQueueRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Tasks_V2beta3_Queue>

  /// Updates a queue.
  ///
  /// This method creates the queue if it does not exist and updates
  /// the queue if it does exist.
  ///
  /// Queues created with this method allow tasks to live for a maximum of 31
  /// days. After a task is 31 days old, the task will be deleted regardless of whether
  /// it was dispatched or not.
  ///
  /// WARNING: Using this method may have unintended side effects if you are
  /// using an App Engine `queue.yaml` or `queue.xml` file to manage your queues.
  /// Read
  /// [Overview of Queue Management and
  /// queue.yaml](https://cloud.google.com/tasks/docs/queue-yaml) before using
  /// this method.
  func updateQueue(request: Google_Cloud_Tasks_V2beta3_UpdateQueueRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Tasks_V2beta3_Queue>

  /// Deletes a queue.
  ///
  /// This command will delete the queue even if it has tasks in it.
  ///
  /// Note: If you delete a queue, a queue with the same name can't be created
  /// for 7 days.
  ///
  /// WARNING: Using this method may have unintended side effects if you are
  /// using an App Engine `queue.yaml` or `queue.xml` file to manage your queues.
  /// Read
  /// [Overview of Queue Management and
  /// queue.yaml](https://cloud.google.com/tasks/docs/queue-yaml) before using
  /// this method.
  func deleteQueue(request: Google_Cloud_Tasks_V2beta3_DeleteQueueRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>

  /// Purges a queue by deleting all of its tasks.
  ///
  /// All tasks created before this method is called are permanently deleted.
  ///
  /// Purge operations can take up to one minute to take effect. Tasks
  /// might be dispatched before the purge takes effect. A purge is irreversible.
  func purgeQueue(request: Google_Cloud_Tasks_V2beta3_PurgeQueueRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Tasks_V2beta3_Queue>

  /// Pauses the queue.
  ///
  /// If a queue is paused then the system will stop dispatching tasks
  /// until the queue is resumed via
  /// [ResumeQueue][google.cloud.tasks.v2beta3.CloudTasks.ResumeQueue]. Tasks can still be added
  /// when the queue is paused. A queue is paused if its
  /// [state][google.cloud.tasks.v2beta3.Queue.state] is [PAUSED][google.cloud.tasks.v2beta3.Queue.State.PAUSED].
  func pauseQueue(request: Google_Cloud_Tasks_V2beta3_PauseQueueRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Tasks_V2beta3_Queue>

  /// Resume a queue.
  ///
  /// This method resumes a queue after it has been
  /// [PAUSED][google.cloud.tasks.v2beta3.Queue.State.PAUSED] or
  /// [DISABLED][google.cloud.tasks.v2beta3.Queue.State.DISABLED]. The state of a queue is stored
  /// in the queue's [state][google.cloud.tasks.v2beta3.Queue.state]; after calling this method it
  /// will be set to [RUNNING][google.cloud.tasks.v2beta3.Queue.State.RUNNING].
  ///
  /// WARNING: Resuming many high-QPS queues at the same time can
  /// lead to target overloading. If you are resuming high-QPS
  /// queues, follow the 500/50/5 pattern described in
  /// [Managing Cloud Tasks Scaling
  /// Risks](https://cloud.google.com/tasks/docs/manage-cloud-task-scaling).
  func resumeQueue(request: Google_Cloud_Tasks_V2beta3_ResumeQueueRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Tasks_V2beta3_Queue>

  /// Gets the access control policy for a [Queue][google.cloud.tasks.v2beta3.Queue].
  /// Returns an empty policy if the resource exists and does not have a policy
  /// set.
  ///
  /// Authorization requires the following
  /// [Google IAM](https://cloud.google.com/iam) permission on the specified
  /// resource parent:
  ///
  /// * `cloudtasks.queues.getIamPolicy`
  func getIamPolicy(request: Google_Iam_V1_GetIamPolicyRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Iam_V1_Policy>

  /// Sets the access control policy for a [Queue][google.cloud.tasks.v2beta3.Queue]. Replaces any existing
  /// policy.
  ///
  /// Note: The Cloud Console does not check queue-level IAM permissions yet.
  /// Project-level permissions are required to use the Cloud Console.
  ///
  /// Authorization requires the following
  /// [Google IAM](https://cloud.google.com/iam) permission on the specified
  /// resource parent:
  ///
  /// * `cloudtasks.queues.setIamPolicy`
  func setIamPolicy(request: Google_Iam_V1_SetIamPolicyRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Iam_V1_Policy>

  /// Returns permissions that a caller has on a [Queue][google.cloud.tasks.v2beta3.Queue].
  /// If the resource does not exist, this will return an empty set of
  /// permissions, not a [NOT_FOUND][google.rpc.Code.NOT_FOUND] error.
  ///
  /// Note: This operation is designed to be used for building permission-aware
  /// UIs and command-line tools, not for authorization checking. This operation
  /// may "fail open" without warning.
  func testIamPermissions(request: Google_Iam_V1_TestIamPermissionsRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Iam_V1_TestIamPermissionsResponse>

  /// Lists the tasks in a queue.
  ///
  /// By default, only the [BASIC][google.cloud.tasks.v2beta3.Task.View.BASIC] view is retrieved
  /// due to performance considerations;
  /// [response_view][google.cloud.tasks.v2beta3.ListTasksRequest.response_view] controls the
  /// subset of information which is returned.
  ///
  /// The tasks may be returned in any order. The ordering may change at any
  /// time.
  func listTasks(request: Google_Cloud_Tasks_V2beta3_ListTasksRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Tasks_V2beta3_ListTasksResponse>

  /// Gets a task.
  func getTask(request: Google_Cloud_Tasks_V2beta3_GetTaskRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Tasks_V2beta3_Task>

  /// Creates a task and adds it to a queue.
  ///
  /// Tasks cannot be updated after creation; there is no UpdateTask command.
  ///
  /// * The maximum task size is 100KB.
  func createTask(request: Google_Cloud_Tasks_V2beta3_CreateTaskRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Tasks_V2beta3_Task>

  /// Deletes a task.
  ///
  /// A task can be deleted if it is scheduled or dispatched. A task
  /// cannot be deleted if it has executed successfully or permanently
  /// failed.
  func deleteTask(request: Google_Cloud_Tasks_V2beta3_DeleteTaskRequest, context: StatusOnlyCallContext) -> EventLoopFuture<SwiftProtobuf.Google_Protobuf_Empty>

  /// Forces a task to run now.
  ///
  /// When this method is called, Cloud Tasks will dispatch the task, even if
  /// the task is already running, the queue has reached its [RateLimits][google.cloud.tasks.v2beta3.RateLimits] or
  /// is [PAUSED][google.cloud.tasks.v2beta3.Queue.State.PAUSED].
  ///
  /// This command is meant to be used for manual debugging. For
  /// example, [RunTask][google.cloud.tasks.v2beta3.CloudTasks.RunTask] can be used to retry a failed
  /// task after a fix has been made or to manually force a task to be
  /// dispatched now.
  ///
  /// The dispatched task is returned. That is, the task that is returned
  /// contains the [status][Task.status] after the task is dispatched but
  /// before the task is received by its target.
  ///
  /// If Cloud Tasks receives a successful response from the task's
  /// target, then the task will be deleted; otherwise the task's
  /// [schedule_time][google.cloud.tasks.v2beta3.Task.schedule_time] will be reset to the time that
  /// [RunTask][google.cloud.tasks.v2beta3.CloudTasks.RunTask] was called plus the retry delay specified
  /// in the queue's [RetryConfig][google.cloud.tasks.v2beta3.RetryConfig].
  ///
  /// [RunTask][google.cloud.tasks.v2beta3.CloudTasks.RunTask] returns
  /// [NOT_FOUND][google.rpc.Code.NOT_FOUND] when it is called on a
  /// task that has already succeeded or permanently failed.
  func runTask(request: Google_Cloud_Tasks_V2beta3_RunTaskRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Google_Cloud_Tasks_V2beta3_Task>
}

extension Google_Cloud_Tasks_V2beta3_CloudTasksProvider {
  public var serviceName: Substring { return "google.cloud.tasks.v2beta3.CloudTasks" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "ListQueues":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_ListQueuesRequest>(),
        responseSerializer: ProtobufSerializer<Google_Cloud_Tasks_V2beta3_ListQueuesResponse>(),
        interceptors: self.interceptors?.makeListQueuesInterceptors() ?? [],
        userFunction: self.listQueues(request:context:)
      )

    case "GetQueue":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_GetQueueRequest>(),
        responseSerializer: ProtobufSerializer<Google_Cloud_Tasks_V2beta3_Queue>(),
        interceptors: self.interceptors?.makeGetQueueInterceptors() ?? [],
        userFunction: self.getQueue(request:context:)
      )

    case "CreateQueue":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_CreateQueueRequest>(),
        responseSerializer: ProtobufSerializer<Google_Cloud_Tasks_V2beta3_Queue>(),
        interceptors: self.interceptors?.makeCreateQueueInterceptors() ?? [],
        userFunction: self.createQueue(request:context:)
      )

    case "UpdateQueue":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_UpdateQueueRequest>(),
        responseSerializer: ProtobufSerializer<Google_Cloud_Tasks_V2beta3_Queue>(),
        interceptors: self.interceptors?.makeUpdateQueueInterceptors() ?? [],
        userFunction: self.updateQueue(request:context:)
      )

    case "DeleteQueue":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_DeleteQueueRequest>(),
        responseSerializer: ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        interceptors: self.interceptors?.makeDeleteQueueInterceptors() ?? [],
        userFunction: self.deleteQueue(request:context:)
      )

    case "PurgeQueue":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_PurgeQueueRequest>(),
        responseSerializer: ProtobufSerializer<Google_Cloud_Tasks_V2beta3_Queue>(),
        interceptors: self.interceptors?.makePurgeQueueInterceptors() ?? [],
        userFunction: self.purgeQueue(request:context:)
      )

    case "PauseQueue":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_PauseQueueRequest>(),
        responseSerializer: ProtobufSerializer<Google_Cloud_Tasks_V2beta3_Queue>(),
        interceptors: self.interceptors?.makePauseQueueInterceptors() ?? [],
        userFunction: self.pauseQueue(request:context:)
      )

    case "ResumeQueue":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_ResumeQueueRequest>(),
        responseSerializer: ProtobufSerializer<Google_Cloud_Tasks_V2beta3_Queue>(),
        interceptors: self.interceptors?.makeResumeQueueInterceptors() ?? [],
        userFunction: self.resumeQueue(request:context:)
      )

    case "GetIamPolicy":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Iam_V1_GetIamPolicyRequest>(),
        responseSerializer: ProtobufSerializer<Google_Iam_V1_Policy>(),
        interceptors: self.interceptors?.makeGetIamPolicyInterceptors() ?? [],
        userFunction: self.getIamPolicy(request:context:)
      )

    case "SetIamPolicy":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Iam_V1_SetIamPolicyRequest>(),
        responseSerializer: ProtobufSerializer<Google_Iam_V1_Policy>(),
        interceptors: self.interceptors?.makeSetIamPolicyInterceptors() ?? [],
        userFunction: self.setIamPolicy(request:context:)
      )

    case "TestIamPermissions":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Iam_V1_TestIamPermissionsRequest>(),
        responseSerializer: ProtobufSerializer<Google_Iam_V1_TestIamPermissionsResponse>(),
        interceptors: self.interceptors?.makeTestIamPermissionsInterceptors() ?? [],
        userFunction: self.testIamPermissions(request:context:)
      )

    case "ListTasks":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_ListTasksRequest>(),
        responseSerializer: ProtobufSerializer<Google_Cloud_Tasks_V2beta3_ListTasksResponse>(),
        interceptors: self.interceptors?.makeListTasksInterceptors() ?? [],
        userFunction: self.listTasks(request:context:)
      )

    case "GetTask":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_GetTaskRequest>(),
        responseSerializer: ProtobufSerializer<Google_Cloud_Tasks_V2beta3_Task>(),
        interceptors: self.interceptors?.makeGetTaskInterceptors() ?? [],
        userFunction: self.getTask(request:context:)
      )

    case "CreateTask":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_CreateTaskRequest>(),
        responseSerializer: ProtobufSerializer<Google_Cloud_Tasks_V2beta3_Task>(),
        interceptors: self.interceptors?.makeCreateTaskInterceptors() ?? [],
        userFunction: self.createTask(request:context:)
      )

    case "DeleteTask":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_DeleteTaskRequest>(),
        responseSerializer: ProtobufSerializer<SwiftProtobuf.Google_Protobuf_Empty>(),
        interceptors: self.interceptors?.makeDeleteTaskInterceptors() ?? [],
        userFunction: self.deleteTask(request:context:)
      )

    case "RunTask":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Google_Cloud_Tasks_V2beta3_RunTaskRequest>(),
        responseSerializer: ProtobufSerializer<Google_Cloud_Tasks_V2beta3_Task>(),
        interceptors: self.interceptors?.makeRunTaskInterceptors() ?? [],
        userFunction: self.runTask(request:context:)
      )

    default:
      return nil
    }
  }
}

public protocol Google_Cloud_Tasks_V2beta3_CloudTasksServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'listQueues'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListQueuesInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_ListQueuesRequest, Google_Cloud_Tasks_V2beta3_ListQueuesResponse>]

  /// - Returns: Interceptors to use when handling 'getQueue'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetQueueInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_GetQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>]

  /// - Returns: Interceptors to use when handling 'createQueue'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateQueueInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_CreateQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>]

  /// - Returns: Interceptors to use when handling 'updateQueue'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpdateQueueInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_UpdateQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>]

  /// - Returns: Interceptors to use when handling 'deleteQueue'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteQueueInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_DeleteQueueRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when handling 'purgeQueue'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePurgeQueueInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_PurgeQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>]

  /// - Returns: Interceptors to use when handling 'pauseQueue'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makePauseQueueInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_PauseQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>]

  /// - Returns: Interceptors to use when handling 'resumeQueue'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeResumeQueueInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_ResumeQueueRequest, Google_Cloud_Tasks_V2beta3_Queue>]

  /// - Returns: Interceptors to use when handling 'getIamPolicy'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetIamPolicyInterceptors() -> [ServerInterceptor<Google_Iam_V1_GetIamPolicyRequest, Google_Iam_V1_Policy>]

  /// - Returns: Interceptors to use when handling 'setIamPolicy'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSetIamPolicyInterceptors() -> [ServerInterceptor<Google_Iam_V1_SetIamPolicyRequest, Google_Iam_V1_Policy>]

  /// - Returns: Interceptors to use when handling 'testIamPermissions'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeTestIamPermissionsInterceptors() -> [ServerInterceptor<Google_Iam_V1_TestIamPermissionsRequest, Google_Iam_V1_TestIamPermissionsResponse>]

  /// - Returns: Interceptors to use when handling 'listTasks'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeListTasksInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_ListTasksRequest, Google_Cloud_Tasks_V2beta3_ListTasksResponse>]

  /// - Returns: Interceptors to use when handling 'getTask'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetTaskInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_GetTaskRequest, Google_Cloud_Tasks_V2beta3_Task>]

  /// - Returns: Interceptors to use when handling 'createTask'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeCreateTaskInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_CreateTaskRequest, Google_Cloud_Tasks_V2beta3_Task>]

  /// - Returns: Interceptors to use when handling 'deleteTask'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeDeleteTaskInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_DeleteTaskRequest, SwiftProtobuf.Google_Protobuf_Empty>]

  /// - Returns: Interceptors to use when handling 'runTask'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeRunTaskInterceptors() -> [ServerInterceptor<Google_Cloud_Tasks_V2beta3_RunTaskRequest, Google_Cloud_Tasks_V2beta3_Task>]
}
